// <auto-generated />
namespace CapaDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CrearTblPedidos_DetallePedidos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CrearTblPedidos_DetallePedidos));
        
        string IMigrationMetadata.Id
        {
            get { return "202007150015340_CrearTblPedidos_DetallePedidos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
